basic.showString("SEMAFOR")
microshield.Servo(microshield.Servos.S0, 0)
tinkercademy.LED(DigitalPin.P0, OnOff.On)
tinkercademy.LED(DigitalPin.P1, OnOff.Off)
tinkercademy.LED(DigitalPin.P2, OnOff.Off)
basic.forever(function () {
    if (pins.digitalReadPin(DigitalPin.P0) == 0) {
        microshield.Servo(microshield.Servos.S0, 90)
        tinkercademy.LED(DigitalPin.P12, OnOff.Off)
        tinkercademy.LED(DigitalPin.P14, OnOff.On)
        basic.pause(3000)
        tinkercademy.LED(DigitalPin.P14, OnOff.Off)
        tinkercademy.LED(DigitalPin.P2, OnOff.On)
        basic.pause(500)
        pins.digitalWritePin(DigitalPin.P0, 1)
    }
    microshield.Servo(microshield.Servos.S0, 0)
    tinkercademy.LED(DigitalPin.P0, OnOff.On)
    tinkercademy.LED(DigitalPin.P2, OnOff.Off)
})
